model:
  width: 64
  num_classes: 10
  num_channels: 3

fine_tune:
  device: "cuda:0"
  du_weights_load_path: "outputs/private/finetuned_model.pth"
  dux_weights_load_dir: "outputs/private_unlearned/"

defense:
  # Pruned models directory
  pruned_weights_load_dir: "outputs/pruned_models/"
  prune_rates: [0.1, 0.25, 0.5, 0.9]
  classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  proportion: [0.003, 0.01, 0.1, 0.25, 0.5, 0.9]
  probe_samples_path: "outputs/probing_samples/"
  results_save_folder: "outputs/defense_results"

analysis:
  save_results: true
  verbose_logging: true

visualization:
  save_dir: "outputs/defense_visualizations"
  create_comparison_plots: true
  create_heatmaps: true