seed: 233

data:
  path: "data"
  public_split: 0.8
  augment: false

attack:
  classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  proportion: [0.1, 0.25, 0.25, 0.9]

fine_tune:
  epochs: 20
  batch_size: 128
  lr: 0.001
  device: 'cuda:0'
  weights_load_path: "outputs/public/pretrained.pth"
  model_save_folder: "outputs/private_unlearned"
  eval_every_n: 5

model:
  width: 64
  num_classes: 10
  num_channels: 3
