seed: 233

data:
  path: "data"
  public_split: 0.8
  augment: false

model:
  width: 64
  num_classes: 10
  num_channels: 3

fine_tune:
  epochs: 20
  batch_size: 128
  lr: 0.001
  device: 'cuda:0'
  weights_load_path: "outputs/public/pretrained.pth"
  model_save_folder: "outputs/private"
  eval_every_n: 1