seed: 233

data:
  path: "./data"
  public_split: 0.8
  augment: true
  class: 0
  proportion: 0.1

model:
  width: 64
  num_classes: 10
  num_channels: 3

train:
  epochs: 120
  batch_size: 128
  lr: 0.1
  weight_decay: 0.0005

fine_tune:
  epochs: 10
  lr: 0.001